import { NextRequest, NextResponse } from "next/server"
import { getServerSession } from "next-auth"
import { authOptions } from "@/lib/auth"
import { prisma } from "@/lib/prisma"

export async function POST(
  request: NextRequest,
  { params }: { params: Promise<{ dealId: string }> }
) {
  try {
    const session = await getServerSession(authOptions)
    if (!session) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
    }

    const { dealId } = await params

    // Get transaction summary
    const summary = await prisma.transactionSummary.findUnique({
      where: { dealId },
    })

    if (!summary) {
      return NextResponse.json(
        { error: "No transaction summary found. Please analyze a contract first." },
        { status: 400 }
      )
    }

    // Get or create timeline
    let timeline = await prisma.timeline.findUnique({
      where: { dealId },
    })

    if (!timeline) {
      timeline = await prisma.timeline.create({
        data: { dealId },
      })
    }

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const rawAnalysis = summary.rawAnalysis as any
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const milestones: any[] = []
    let sortOrder = 0

    // Helper to add milestone
    const addMilestone = (
      name: string,
      dueDate: Date | null,
      description?: string,
      parentId?: string
    ) => {
      if (dueDate) {
        sortOrder++
        milestones.push({
          name,
          description,
          dueDate,
          timelineId: timeline!.id,
          parentId: parentId || null,
          sortOrder,
          isAutoGenerated: true,
          sourceType: "CONTRACT_ANALYSIS",
          reminderDays: [7, 3, 1],
        })
      }
    }

    // Add key dates as milestones
    if (summary.effectiveDate) {
      addMilestone("Effective Date", summary.effectiveDate)
    }

    if (summary.feasibilityExpiration) {
      addMilestone(
        "Feasibility Period Expires",
        summary.feasibilityExpiration,
        `${summary.feasibilityPeriodDays} day feasibility period`
      )
    }

    // Add contingencies
    if (rawAnalysis.contingencies) {
      for (const contingency of rawAnalysis.contingencies) {
        const deadline = contingency.deadline
          ? new Date(contingency.deadline)
          : null
        addMilestone(contingency.name, deadline, contingency.description)
      }
    }

    // Add title/survey deadlines
    if (rawAnalysis.titleCommitmentDays && summary.effectiveDate) {
      const titleDate = new Date(summary.effectiveDate)
      titleDate.setDate(titleDate.getDate() + rawAnalysis.titleCommitmentDays)
      addMilestone("Title Commitment Due", titleDate)
    }

    if (rawAnalysis.surveyDays && summary.effectiveDate) {
      const surveyDate = new Date(summary.effectiveDate)
      surveyDate.setDate(surveyDate.getDate() + rawAnalysis.surveyDays)
      addMilestone("Survey Due", surveyDate)
    }

    if (rawAnalysis.titleObjectionDays && summary.effectiveDate) {
      const objectionDate = new Date(summary.effectiveDate)
      objectionDate.setDate(objectionDate.getDate() + rawAnalysis.titleObjectionDays)
      addMilestone("Title Objection Deadline", objectionDate)
    }

    // Add closing date
    if (summary.closingDate) {
      addMilestone("Closing Date", summary.closingDate, "Execute closing documents")
    }

    if (summary.outsideClosingDate) {
      addMilestone("Outside Closing Date", summary.outsideClosingDate, "Final deadline for closing")
    }

    // Create all milestones
    if (milestones.length > 0) {
      await prisma.milestone.createMany({
        data: milestones,
      })
    }

    return NextResponse.json({
      success: true,
      message: `Created ${milestones.length} milestones from contract analysis`,
      count: milestones.length,
    })
  } catch (error) {
    console.error("Error generating timeline:", error)
    return NextResponse.json(
      { error: "Failed to generate timeline" },
      { status: 500 }
    )
  }
}
