import { NextRequest, NextResponse } from "next/server"
import { getServerSession } from "next-auth"
import { authOptions } from "@/lib/auth"
import { prisma } from "@/lib/prisma"
import { z } from "zod"
import { ACQUISITION_TEMPLATE, instantiateTemplate } from "@/lib/milestoneTemplates"

const applyTemplateSchema = z.object({
  templateType: z.enum(["ACQUISITION", "DISPOSITION"]),
  effectiveDate: z.string().min(1, "Effective date is required"),
  closingDate: z.string().min(1, "Closing date is required"),
  clearExisting: z.boolean().optional(),
})

export async function POST(
  request: NextRequest,
  { params }: { params: Promise<{ dealId: string }> }
) {
  try {
    const session = await getServerSession(authOptions)
    if (!session) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
    }

    const { dealId } = await params
    const body = await request.json()
    const data = applyTemplateSchema.parse(body)

    // Get or create timeline
    let timeline = await prisma.timeline.findUnique({
      where: { dealId },
    })

    if (!timeline) {
      timeline = await prisma.timeline.create({
        data: { dealId },
      })
    }

    // Clear existing milestones if requested
    if (data.clearExisting) {
      await prisma.milestone.deleteMany({
        where: { timelineId: timeline.id },
      })
    }

    // Select template
    const template = data.templateType === "ACQUISITION"
      ? ACQUISITION_TEMPLATE
      : ACQUISITION_TEMPLATE // TODO: Add disposition template

    // Instantiate template with dates
    const effectiveDate = new Date(data.effectiveDate)
    const closingDate = new Date(data.closingDate)
    const milestones = instantiateTemplate(template, effectiveDate, closingDate)

    // Create milestones
    let sortOrder = 0
    for (const milestone of milestones) {
      sortOrder++
      const created = await prisma.milestone.create({
        data: {
          name: milestone.name,
          description: milestone.description,
          dueDate: milestone.dueDate,
          timelineId: timeline.id,
          sortOrder,
          isAutoGenerated: true,
          sourceType: "TEMPLATE",
          sourceReference: data.templateType,
          reminderDays: [7, 3, 1],
        },
      })

      // Create children
      if (milestone.children) {
        let childSortOrder = 0
        for (const child of milestone.children) {
          childSortOrder++
          await prisma.milestone.create({
            data: {
              name: child.name,
              description: child.description,
              dueDate: child.dueDate,
              timelineId: timeline.id,
              parentId: created.id,
              sortOrder: childSortOrder,
              isAutoGenerated: true,
              sourceType: "TEMPLATE",
              sourceReference: data.templateType,
              reminderDays: [3, 1],
            },
          })
        }
      }
    }

    return NextResponse.json({ success: true, message: "Template applied successfully" })
  } catch (error) {
    if (error instanceof z.ZodError) {
      return NextResponse.json(
        { error: error.issues[0].message },
        { status: 400 }
      )
    }
    console.error("Error applying template:", error)
    return NextResponse.json(
      { error: "Failed to apply template" },
      { status: 500 }
    )
  }
}
